export const generateMockChannel = () => ({
  initialized: true,
  loading: false,
  currentGroupChannel: {
    url: 'sendbird_group_channel_13883929_3dc3bb3af92eded8ff8e5f71de775fe149a32dd6',
  },
  messageListParams: null,
  lastMessageTimeStamp: 0,
  latestFetchedMessageTimeStamp: 1582004042250,
  allMessages: [{
    "messageId": 390280166,
    "messageType": "user",
    "channelUrl": "sendbird_group_channel_13883929_3dc3bb3af92eded8ff8e5f71de775fe149a32dd6",
    "data": "",
    "customType": "",
    "createdAt": 1582004042250,
    "updatedAt": 0,
    "channelType": "group",
    "metaArrays": [],
    "reactions": [],
    "mentionType": "users",
    "mentionedUsers": [],
    "message": "139",
    "_sender": {
      "nickname": "nick",
      "profileUrl": "",
      "userId": "user123",
      "connectionStatus": "nonavailable",
      "lastSeenAt": 0,
      "metaData": {},
      "isActive": true,
      "friendDiscoveryKey": null,
      "friendName": null,
      "_preferredLanguages": null,
      "isBlockedByMe": false
    },
    "reqId": "1582003170227",
    "translations": {},
    "requestState": "succeeded",
    "requestedMentionUserIds": [],
    "errorCode": 0,
    "sendingStatus": 'succeeded',
  }, {
    "messageId": 390282403,
    "messageType": "user",
    "channelUrl": "sendbird_group_channel_13883929_3dc3bb3af92eded8ff8e5f71de775fe149a32dd6",
    "data": "",
    "customType": "",
    "createdAt": 1582004195477,
    "updatedAt": 0,
    "channelType": "group",
    "metaArrays": [],
    "reactions": [],
    "mentionType": "users",
    "mentionedUsers": [],
    "message": "140",
    "_sender": {
      "nickname": "nick",
      "profileUrl": "",
      "userId": "user123",
      "connectionStatus": "nonavailable",
      "lastSeenAt": 0,
      "metaData": {},
      "isActive": true,
      "friendDiscoveryKey": null,
      "friendName": null,
      "_preferredLanguages": null,
      "isBlockedByMe": false
    },
    "reqId": "1582004163918",
    "translations": {},
    "requestState": "succeeded",
    "requestedMentionUserIds": [],
    "errorCode": 0,
    "sendingStatus": 'succeeded',
  }, {
    "messageId": 390282693,
    "messageType": "user",
    "channelUrl": "sendbird_group_channel_13883929_3dc3bb3af92eded8ff8e5f71de775fe149a32dd6",
    "data": "",
    "customType": "",
    "createdAt": 1582004214188,
    "updatedAt": 0,
    "channelType": "group",
    "metaArrays": [],
    "reactions": [],
    "mentionType": "users",
    "mentionedUsers": [],
    "message": "141",
    "_sender": {
      "nickname": "nick",
      "profileUrl": "",
      "userId": "user123",
      "connectionStatus": "nonavailable",
      "lastSeenAt": 0,
      "metaData": {},
      "isActive": true,
      "friendDiscoveryKey": null,
      "friendName": null,
      "_preferredLanguages": null,
      "isBlockedByMe": false
    },

    "reqId": "1582004210491",
    "translations": {},
    "requestState": "succeeded",
    "requestedMentionUserIds": [],
    "errorCode": 0,
    "sendingStatus": 'succeeded',
  }],
  hasMore: true,
});

export const generateMockMessage = (id) => {
  const mockMessage = {
    "messageId": id,
    "messageType": "user",
    "channelUrl": "sendbird_group_channel_13883929_3dc3bb3af92eded8ff8e5f71de775fe149a32dd6",
    "data": "",
    "customType": "",
    "createdAt": 1582004961420,
    "updatedAt": 0,
    "channelType": "group",
    "metaArrays": [],
    reactions: [],
    "mentionType": "users",
    "mentionedUsers": [],
    "message": "146",
    "_sender": {},
    "reqId": "1582004949355",
    "translations": {},
    "requestState": "succeeded",
    "requestedMentionUserIds": [],
    "errorCode": 0,
    applyReactionEvent: (reactionEvent) => {
      // mock for SDK
      mockMessage.reactions = reactionEvent.reactions;
    },
  };
  return mockMessage;
}
export const mockMessage1 = {
  "messageId": 390292882,
  "messageType": "user",
  "channelUrl": "sendbird_group_channel_13883929_3dc3bb3af92eded8ff8e5f71de775fe149a32dd6",
  "data": "",
  "customType": "",
  "createdAt": 1582004961420,
  "updatedAt": 0,
  "channelType": "group",
  "metaArrays": [],
  "reactions": [],
  "mentionType": "users",
  "mentionedUsers": [],
  "message": "146",
  "_sender": {
    "nickname": "nick",
    "profileUrl": "",
    "userId": "user123",
    "connectionStatus": "nonavailable",
    "lastSeenAt": 0,
    "metaData": {},
    "isActive": true,
    "friendDiscoveryKey": null,
    "friendName": null,
    "_preferredLanguages": null,
    "isBlockedByMe": false
  },
  "reqId": "1582004949355",
  "translations": {},
  "requestState": "succeeded",
  "requestedMentionUserIds": [],
  "errorCode": 0
};

export const frozenChannel = {
  "url": "sendbird_group_channel_204619489_3df4fd3d2feeef8bb0775e57950784a92fa3184c",
  "channelType": "group",
  "name": "",
  "coverUrl": "",
  "createdAt": 1591171555000,
  "data": "",
  "customType": "",
  "isFrozen": true,
  "isEphemeral": false,
  "isDistinct": false,
  "isSuper": false,
  "isBroadcast": false,
  "isPublic": false,
  "unreadMessageCount": 0,
  "inviter": {},
  "members": [],
  "memberMap": {},
  "lastMessage": {},
  "memberCount": 11,
  "joinedMemberCount": 11,
  "cachedDeliveryReceiptStatus": null,
  "myPushTriggerOption": "default",
  "isHidden": false,
  "hiddenState": "unhidden",
  "isDiscoverable": false,
  "myLastRead": 1591264134976,
  "messageSurvivalSeconds": -1,
  "_messageOffsetTimestamp": 0,
  "_cachedLastDeliveredReceipt": {
    "sentAt": 0,
    "timeout": null
  },
  "isAccessCodeRequired": false,
  "isPushEnabled": true,
  "myCountPreference": "all",
  "unreadMentionCount": 0,
  "myMemberState": "joined",
  "myRole": "operator",
  "myMutedState": "unmuted",
  "invitedAt": 1591171555307
};
