const IMAGE_GRID_WIDTH = 400;
const PADDING = 4;
const GAP = 4;
const MESSAGE_CONTENT_SIDE_PADDING = 28;
const MARGIN_LEFT = 12;
const PROFILE_IMAGE_WIDTH = 40;
const THREAD_WIDTH = 320;

export const MULTIPLE_FILES_IMAGE_SIDE_LENGTH = `calc(${IMAGE_GRID_WIDTH / 2}px 
- ${2 * (PADDING / 2)}px - ${GAP / 2}px)`;
export const MULTIPLE_FILES_IMAGE_SIDE_LENGTH_THREAD = `calc(${(THREAD_WIDTH / 2) 
- (MESSAGE_CONTENT_SIDE_PADDING / 2 + PROFILE_IMAGE_WIDTH / 2 + MARGIN_LEFT / 2 + GAP / 2)}px)`;
export const MULTIPLE_FILES_IMAGE_SIDE_LENGTH_THREAD_MOBILE = `calc(50vw 
- ${MESSAGE_CONTENT_SIDE_PADDING / 2 + PROFILE_IMAGE_WIDTH / 2 + MARGIN_LEFT / 2 + GAP / 2}px)`;
export const MULTIPLE_FILES_IMAGE_BORDER_RADIUS = '6px';
export const MULTIPLE_FILES_IMAGE_BORDER_RADIUS_THREAD = '8px';
export const MULTIPLE_FILES_IMAGE_THUMBNAIL_SIDE_LENGTH = '40px';
