const GRID_WIDTH_CHAT_WEB = 400;
const GRID_SIDE_PADDING = 8;
const GRID_GAP = 4;
const TIMESTAMP_WIDTH_AND_ITS_SIDE_MARGIN_WEB_MOBILE = 54;
const MARGIN_LEFT = 12;
const PROFILE_IMAGE_WIDTH = 40;
const THREAD_WIDTH = 320;
const CHAT_BODY_SIDE_PADDING = 48;

const THREAD_CHILD_WIDTH = 200;
const THREAD_CHILD_SIDE_PADDING = 8;

const THREAD_CHILD_MOBILE_SIDE_PADDING = 32;
const THREAD_CHILD_MOBILE_TIMESTAMP_WIDTH_AND_ITS_SIDE_MARGIN = 60;

export const MULTIPLE_FILES_IMAGE_SIDE_LENGTH = {
  CHAT_WEB: `calc(${GRID_WIDTH_CHAT_WEB / 2}px - ${(GRID_SIDE_PADDING + GRID_GAP) / 2}px)`,
  CHAT_MOBILE: `calc(50vw - ${(CHAT_BODY_SIDE_PADDING + PROFILE_IMAGE_WIDTH + TIMESTAMP_WIDTH_AND_ITS_SIDE_MARGIN_WEB_MOBILE + GRID_SIDE_PADDING + GRID_GAP) / 2}px)`,
  THREAD_PARENT_WEB: `calc(${(THREAD_WIDTH / 2) - (TIMESTAMP_WIDTH_AND_ITS_SIDE_MARGIN_WEB_MOBILE / 2 + PROFILE_IMAGE_WIDTH / 2 + MARGIN_LEFT / 2 + GRID_GAP / 2)}px)`,
  THREAD_PARENT_MOBILE: `calc(50vw - ${TIMESTAMP_WIDTH_AND_ITS_SIDE_MARGIN_WEB_MOBILE / 2 + PROFILE_IMAGE_WIDTH / 2 + MARGIN_LEFT / 2 + GRID_GAP / 2}px)`,
  THREAD_CHILD_WEB: `calc(${(THREAD_CHILD_WIDTH - THREAD_CHILD_SIDE_PADDING - GRID_GAP) / 2}px)`,
  THREAD_CHILD_MOBILE: `calc(50vw - ${(THREAD_CHILD_MOBILE_SIDE_PADDING + PROFILE_IMAGE_WIDTH + THREAD_CHILD_MOBILE_TIMESTAMP_WIDTH_AND_ITS_SIDE_MARGIN + GRID_SIDE_PADDING + GRID_GAP) / 2}px)`,
};
export const MULTIPLE_FILES_IMAGE_BORDER_RADIUS = {
  CHAT_WEB: '6px',
  CHAT_MOBILE: '6px',
  THREAD_PARENT_WEB: '6px',
  THREAD_PARENT_MOBILE: '6px',
  THREAD_CHILD_WEB: '6px',
  THREAD_CHILD_MOBILE: '6px',
};
export const MULTIPLE_FILES_IMAGE_THUMBNAIL_SIDE_LENGTH = '40px';
