export enum ThreadContextActionTypes {
  GET_CHANNEL_START = 'GET_CHANNEL_START',
  GET_CHANNEL_SUCCESS = 'GET_CHANNEL_SUCCESS',
  GET_CHANNEL_FAILURE = 'GET_CHANNEL_FAILURE',

  GET_PARENT_MESSAGE_START = 'GET_PARENT_MESSAGE_START',
  GET_PARENT_MESSAGE_SUCCESS = 'GET_PARENT_MESSAGE_SUCCESS',
  GET_PARENT_MESSAGE_FAILURE = 'GET_PARENT_MESSAGE_FAILURE',

  GET_PREV_MESSAGES_START = 'GET_PREV_MESSAGES_START',
  GET_PREV_MESSAGES_SUCESS = 'GET_PREV_MESSAGES_SUCESS',
  GET_PREV_MESSAGES_FAILURE = 'GET_PREV_MESSAGES_FAILURE',
  GET_NEXT_MESSAGES_START = 'GET_NEXT_MESSAGES_START',
  GET_NEXT_MESSAGES_SUCESS = 'GET_NEXT_MESSAGES_SUCESS',
  GET_NEXT_MESSAGES_FAILURE = 'GET_NEXT_MESSAGES_FAILURE',
  RESET_MESSAGES = 'RESET_MESSAGES',

  SEND_MESSAGE_START = 'SEND_MESSAGE_START',
  SEND_MESSAGE_SUCESS = 'SEND_MESSAGE_SUCESS',
  SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE',
  RESEND_MESSAGE_START = 'RESEND_MESSAGE_START',

  EDIT_MESSAGE = 'EDIT_MESSAGE',
  DELETE_MESSAGE = 'DELETE_MESSAGE',

  // event handlers
  ON_MESSAGE_RECEIVED = 'ON_MESSAGE_RECEIVED',
  ON_MESSAGE_UPDATED = 'ON_MESSAGE_UPDATED',
  ON_MESSAGE_DELETED = 'ON_MESSAGE_DELETED',

  ON_USER_BANNED = 'ON_USER_BANNED',
  ON_USER_MUTED = 'ON_USER_MUTED',
  ON_CHANNEL_FROZEN = 'ON_CHANNEL_FROZEN',
}
