export const RESET_MESSAGES = 'RESET_MESSAGES' as const;

export const FETCH_INITIAL_MESSAGES_START = 'FETCH_INITIAL_MESSAGES_START' as const;
export const FETCH_INITIAL_MESSAGES_SUCCESS = 'FETCH_INITIAL_MESSAGES_SUCCESS' as const;

export const FETCH_INITIAL_MESSAGES_FAILURE = 'FETCH_INITIAL_MESSAGES_FAILURE' as const;
export const FETCH_PREV_MESSAGES_SUCCESS = 'FETCH_PREV_MESSAGES_SUCCESS' as const;
export const FETCH_PREV_MESSAGES_FAILURE = 'FETCH_PREV_MESSAGES_FAILURE' as const;
export const FETCH_NEXT_MESSAGES_SUCCESS = 'FETCH_NEXT_MESSAGES_SUCCESS' as const;
export const FETCH_NEXT_MESSAGES_FAILURE = 'FETCH_NEXT_MESSAGES_FAILURE' as const;

export const SEND_MESSAGE_START = 'SEND_MESSAGE_START' as const;
export const SEND_MESSAGE_SUCESS = 'SEND_MESSAGE_SUCESS' as const;
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE' as const;

export const RESEND_MESSAGE_START = 'RESEND_MESSAGE_START' as const;

export const ON_MESSAGE_RECEIVED = 'ON_MESSAGE_RECEIVED' as const;
export const ON_MESSAGE_UPDATED = 'ON_MESSAGE_UPDATED' as const;
export const ON_MESSAGE_THREAD_INFO_UPDATED = 'ON_MESSAGE_THREAD_INFO_UPDATED' as const;
export const ON_MESSAGE_DELETED = 'ON_MESSAGE_DELETED' as const;
export const ON_MESSAGE_DELETED_BY_REQ_ID = 'ON_MESSAGE_DELETED_BY_REQ_ID' as const;

export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL' as const;
export const SET_CHANNEL_INVALID = 'SET_CHANNEL_INVALID' as const;
export const MARK_AS_READ = 'MARK_AS_READ' as const;

export const ON_REACTION_UPDATED = 'ON_REACTION_UPDATED' as const;
export const SET_EMOJI_CONTAINER = 'SET_EMOJI_CONTAINER' as const;

export const MESSAGE_LIST_PARAMS_CHANGED = 'MESSAGE_LIST_PARAMS_CHANGED' as const;

export const ON_FILE_INFO_UPLOADED = 'ON_FILE_INFO_UPLOADED' as const;
