import { CreateAction } from '../../../utils/typeHelpers/reducers/createAction';
import { UIKitConfigInfo } from './types';

export const UIKIT_CONFIGURATION_ACTIONS = {
  INIT_UIKIT_CONFIGURATION: 'INIT_UIKIT_CONFIGURATION',
  RESET_UIKIT_CONFIGURATION: 'RESET_UIKIT_CONFIGURATION',
} as const;

type UIKIT_CONFIGURATION_PAYLOAD_TYPES = {
  [UIKIT_CONFIGURATION_ACTIONS.INIT_UIKIT_CONFIGURATION]: UIKitConfigInfo
  [UIKIT_CONFIGURATION_ACTIONS.RESET_UIKIT_CONFIGURATION]: null,
};

export type UikitConfigurationActionTypes = CreateAction<UIKIT_CONFIGURATION_PAYLOAD_TYPES>;
