export const dummyMessageTemplateMessageOne = {
  _iid: '58137-1582767006944',
  messageId: 5428660254,
  messageType: 'admin',
  channelUrl: 'app-544C81B3-7159-4662-899D-7A33B6344F37-inbox',
  createdAt: 1686885331048,
  updatedAt: 0,
  message: 'Get Fit with Sendbird Fitness!',
  customType: 'Promotion',
  data: '{"colorVariables":{"SBCOLOR_bg":"#FFECEB,#EF5962","SBCOLOR_title":"#EF5962,#E0FFFFFF","SBCOLOR_text":"#E0000000,#E0FFFFFF","SBCOLOR_blbl":"#FFFFFF,#EF5962","SBCOLOR_bbg":"#EF5962,#FFFFFF"}}',
  mentionType: 'users',
  mentionedUsers: [],
  channelType: 'group',
  extendedMessagePayload: {
    sub_type: 0,
    sub_data: '{"version":1,"body":{"items":[{"type":"box","viewStyle":{"backgroundColor":"{SBCOLOR_bg}"},"layout":"column","width":{"type":"flex","value":0},"height":{"type":"flex","value":1},"items":[{"type":"image","imageUrl":"https://ddtyj01cn62am.cloudfront.net/notifications/chat-example-promotion-fitness.jpg","metaData":{"pixelWidth":984,"pixelHeight":543},"imageStyle":{"contentMode":"aspectFill"}},{"type":"box","layout":"column","viewStyle":{"padding":{"top":12,"right":12,"bottom":12,"left":12}},"items":[{"type":"text","viewStyle":{"margin":{"top":0,"right":8,"bottom":6,"left":0}},"textStyle":{"weight":"bold","size":20,"color":"{SBCOLOR_title}"},"text":"Get Fit with Sendbird Fitness!","maxTextLines":2},{"type":"text","viewStyle":{"margin":{"top":0,"right":16,"bottom":12,"left":0}},"textStyle":{"size":14,"color":"{SBCOLOR_text}"},"text":"Take your fitness routine to the next level with Sendbird Fitness! Click below to chat with one of our experts and learn how we can help you reach your fitness goals.","maxTextLines":6},{"type":"box","layout":"column","items":[{"type":"textButton","text":"Learn more","height":{"type":"fixed","value":36},"viewStyle":{"radius":16,"backgroundColor":"{SBCOLOR_bbg}"},"textStyle":{"weight":"bold","size":14,"color":"{SBCOLOR_blbl}"},"action":{"type":"web","data":"https://sendbird.com/products/notifications"}},{"type":"textButton","text":"Start Chat","height":{"type":"fixed","value":36},"textStyle":{"weight":"bold","size":14,"color":"{SBCOLOR_blbl}"},"viewStyle":{"margin":{"top":8,"right":0,"bottom":0,"left":0},"radius":16,"backgroundColor":"{SBCOLOR_bbg}"},"action":{"type":"web","data":"https://sendbird.com/products/notifications"}}]}]}]}]}}',
  },
  isAdminMessage: (): boolean => true,
};

export const dummyMessageTemplateMessageTwo = {
  _iid: '58137-1582767006944',
  messageId: 5433315903,
  messageType: 'admin',
  channelUrl: 'app-94EA049D-B97D-4A39-A6C9-051BB69A8A05-feed',
  createdAt: 1686958456265,
  updatedAt: 0,
  message: 'Your order has been processed.',
  customType: 'Order details',
  data: '{"colorVariables":{"SBCOLOR_bg":"#F6EFD8,#2D2928","SBCOLOR_text":"#E0000000,#E0FFFFFF","SBCOLOR_blbl":"#E0FFFFFF,#000000","SBCOLOR_bbg":"#63922A,#ADCC88"}}',
  mentionType: 'users',
  mentionedUsers: [],
  channelType: 'group',
  extendedMessagePayload: {
    sub_type: 0,
    sub_data: '{"version":1,"body":{"items":[{"type":"box","viewStyle":{"padding":{"top":12,"right":12,"bottom":12,"left":12},"backgroundColor":"{SBCOLOR_bg}"},"width":{"type":"flex","value":0},"height":{"type":"flex","value":1},"layout":"column","items":[{"type":"text","viewStyle":{"margin":{"top":0,"right":0,"bottom":6,"left":0}},"textStyle":{"weight":"bold","size":20,"color":"{SBCOLOR_text}"},"text":"Your order #123456 has been processed","maxTextLines":3},{"type":"text","viewStyle":{"margin":{"top":0,"right":0,"bottom":16,"left":0}},"textStyle":{"size":14,"color":"{SBCOLOR_text}"},"text":"Your order has been successfully processed and will be shipped via USPS within the next 24 hours. Click to track your order status.","maxTextLines":6},{"type":"box","layout":"row","align":{"horizontal":"left","vertical":"center"},"items":[{"type":"image","metaData":{"pixelWidth":120,"pixelHeight":120},"width":{"type":"fixed","value":40},"height":{"type":"fixed","value":40},"imageUrl":"https://ddtyj01cn62am.cloudfront.net/notifications/feed-example-order-details-product.jpg","imageStyle":{"contentMode":"aspectFill"},"viewStyle":{"radius":20}},{"type":"box","layout":"column","width":{"type":"flex","value":0},"viewStyle":{"margin":{"top":0,"right":0,"bottom":0,"left":12}},"items":[{"type":"text","text":"Goat\'s Milk Soap, Citrus, 3oz Bar","maxTextLines":1,"textStyle":{"weight":"bold","size":16,"color":"{SBCOLOR_text}"},"viewStyle":{"margin":{"top":0,"right":0,"bottom":4,"left":0}}},{"type":"text","text":"Items Total (1)","maxTextLines":1,"textStyle":{"size":14,"color":"{SBCOLOR_text}"}}]}]},{"type":"box","layout":"row","viewStyle":{"margin":{"top":16,"right":0,"bottom":0,"left":0}},"items":[{"type":"textButton","text":"View Receipt","width":{"type":"flex","value":0},"viewStyle":{"padding":{"top":10,"right":20,"bottom":10,"left":20},"radius":6,"backgroundColor":"{SBCOLOR_bbg}"},"textStyle":{"weight":"bold","size":14,"color":"{SBCOLOR_blbl}"},"action":{"type":"web","data":"https://sendbird.com/products/notifications"}},{"type":"textButton","text":"Track Order","width":{"type":"flex","value":0},"textStyle":{"weight":"bold","size":14,"color":"{SBCOLOR_blbl}"},"viewStyle":{"margin":{"top":0,"right":0,"bottom":0,"left":8},"padding":{"top":10,"right":20,"bottom":10,"left":20},"radius":6,"backgroundColor":"{SBCOLOR_bbg}"},"action":{"type":"web","data":"https://sendbird.com/products/notifications"}}]}]}]}}',
  },
  isAdminMessage: (): boolean => true,
};

export const mockBaseMessage = {
  channelUrl: '',
  channelType: 'group',
  messageId: -1,
  createdAt: -1,
  isIdentical: () => false,
  isEqual: () => false,
  isUserMessage: () => false,
  isFileMessage: () => false,
  isAdminMessage: () => false,
  isMultipleFilesMessage: () => false,
  serialize: () => ({}),
  getMetaArraysByKeys: () => [],
  applyThreadInfoUpdateEvent: () => false,
  applyReactionEvent: () => {},
  applyParentMessage: () => false,
};
