enum OpenChannelListActionTypes {
  // actions
  INIT_OPEN_CHANNEL_LIST_START,
  INIT_OPEN_CHANNEL_LIST_SUCCESS,
  INIT_OPEN_CHANNEL_LIST_FAILURE,
  RESET_OPEN_CHANNEL_LIST,
  FETCH_OPEN_CHANNEL_LIST_START,
  FETCH_OPEN_CHANNEL_LIST_SUCCESS,
  FETCH_OPEN_CHANNEL_LIST_FAILURE,
  CREATE_OPEN_CHANNEL,
  SET_CURRENT_OPEN_CHANNEL,
  UPDATE_OPEN_CHANNEL_LIST_QUERY,
}

export default OpenChannelListActionTypes;
