#!/bin/bash
current_branch=$(git symbolic-ref --short HEAD)

# Prevent push to main branch
if [ "$current_branch" = "main" ]; then
  echo "Push to main branch is not allowed"
  exit 1
fi

# Run lint:fix and test scripts
if ! (echo "Running ESLint..." && yarn run lint:fix) ; then
  echo "Linting failed, push not allowed"
  exit 1
fi 

# if ! yarn test ; then
#   echo "Tests failed, push not allowed"
#   exit 1
# fi
