on:
  issue_comment:
    types: [created, edited]

jobs:
    coverage:
        runs-on: ubuntu-latest
        if: github.event.issue.pull_request && contains(github.event.comment.body, './coverage')
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
